Repository ReadingTowns/Backend, pull requests merged in 2025-08, with the labels that each got.

#29 Feat: 온보딩 api 개발 및 Member, Book 엔티티 필드 수정
  api/src/main/resources/application-local.yml
  api/src/main/resources/application-s3.yml
  api/src/main/resources/application.yml
  book/src/main/java/kr/co/readingtown/book/domain/Book.java
  book/src/main/java/kr/co/readingtown/book/domain/SourceFieldType.java
  common/build.gradle
  common/src/main/java/kr/co/readingtown/common/config/AppProperties.java
  member/src/main/java/kr/co/readingtown/member/domain/Member.java
  member/src/main/java/kr/co/readingtown/member/dto/DefaultProfileResponseDto.java
  member/src/main/java/kr/co/readingtown/member/dto/OnboardingRequestDto.java
  member/src/main/java/kr/co/readingtown/member/exception/MemberErrorCode.java
  member/src/main/java/kr/co/readingtown/member/exception/MemberException.java
  member/src/main/java/kr/co/readingtown/member/externalapi/ExternalMemberController.java
  member/src/main/java/kr/co/readingtown/member/repository/MemberRepository.java
  member/src/main/java/kr/co/readingtown/member/service/MemberService.java
Labels: ✨feat, 🛠️fix

#35 Fix: swagger 패키지 스캔, 에러 로그 추가
  api/build.gradle
  api/src/main/java/kr/co/readingtown/response/CustomResponseBodyAdvice.java
  api/src/main/java/kr/co/readingtown/swagger/SwaggerConfig.java
  api/src/main/resources/application-local.yml
  api/src/main/resources/application-prod.yml
  common/src/main/java/kr/co/readingtown/common/exception/GlobalExceptionHandler.java
  common/src/main/java/kr/co/readingtown/common/exception/httpError/HttpErrorCode.java
  common/src/main/java/kr/co/readingtown/common/log/LogInfo.java
  common/src/main/java/kr/co/readingtown/common/log/LogLevel.java
  common/src/main/java/kr/co/readingtown/common/log/LogUtil.java
  common/src/main/java/kr/co/readingtown/common/response/CommonResponse.java
Labels: 🛠️fix

#36 Feat: Book API
  api/src/main/java/kr/co/readingtown/config/SecurityWebConfig.java
  api/src/main/java/kr/co/readingtown/swagger/SwaggerConfig.java
  book/src/main/java/kr/co/readingtown/book/dto/query/BookInfoDto.java
  book/src/main/java/kr/co/readingtown/book/dto/response/BookResponseDto.java
  book/src/main/java/kr/co/readingtown/book/exception/BookErrorCode.java
  book/src/main/java/kr/co/readingtown/book/exception/BookException.java
  book/src/main/java/kr/co/readingtown/book/externalapi/ExternalBookController.java
  book/src/main/java/kr/co/readingtown/book/internalapi/InternalBookController.java
  book/src/main/java/kr/co/readingtown/book/repository/BookRepository.java
  book/src/main/java/kr/co/readingtown/book/service/BookService.java
  member/src/main/java/kr/co/readingtown/member/dto/query/MemberIdNameDto.java
  member/src/main/java/kr/co/readingtown/member/internalapi/InternalMemberController.java
  member/src/main/java/kr/co/readingtown/member/repository/MemberRepository.java
  member/src/main/java/kr/co/readingtown/member/service/MemberService.java
  review/src/main/java/kr/co/readingtown/review/domain/Review.java
  review/src/main/java/kr/co/readingtown/review/dto/query/ReviewContentAndAuthorNameDto.java
  review/src/main/java/kr/co/readingtown/review/dto/query/ReviewIdAndContentDto.java
  review/src/main/java/kr/co/readingtown/review/dto/request/ReviewRequestDto.java
  review/src/main/java/kr/co/readingtown/review/dto/response/ReviewResponseDto.java
  review/src/main/java/kr/co/readingtown/review/dto/response/ReviewWithAuthorResponseDto.java
  review/src/main/java/kr/co/readingtown/review/exception/ReviewErrorCode.java
  review/src/main/java/kr/co/readingtown/review/exception/ReviewException.java
  review/src/main/java/kr/co/readingtown/review/externalapi/ExternalReviewController.java
  review/src/main/java/kr/co/readingtown/review/integration/book/BookClient.java
  review/src/main/java/kr/co/readingtown/review/integration/book/BookValidator.java
  review/src/main/java/kr/co/readingtown/review/integration/member/MemberClient.java
  review/src/main/java/kr/co/readingtown/review/integration/member/MemberReader.java
  review/src/main/java/kr/co/readingtown/review/integration/member/MemberValidator.java
  review/src/main/java/kr/co/readingtown/review/repository/ReviewRepository.java
  review/src/main/java/kr/co/readingtown/review/service/ReviewService.java
Labels: ✨feat

#39 Feat/33 Member 및 Social 도메인 API 구현
  api/src/main/resources/application-kakao-map.yml
  api/src/main/resources/application.yml
  bookhouse/src/main/java/kr/co/readingtown/bookhouse/domain/Bookhouse.java
  bookhouse/src/main/java/kr/co/readingtown/bookhouse/domain/IsExchanged.java
  bookstore/build.gradle
  bookstore/src/main/java/kr/co/readingtown/bookstore/domain/Bookstore.java
  bookstore/src/main/java/kr/co/readingtown/bookstore/domain/BookstoreBook.java
  member/build.gradle
  member/src/main/java/kr/co/readingtown/member/client/BookhouseClient.java
  member/src/main/java/kr/co/readingtown/member/client/FollowClient.java
  member/src/main/java/kr/co/readingtown/member/domain/Member.java
  member/src/main/java/kr/co/readingtown/member/dto/OnboardingRequestDto.java
  member/src/main/java/kr/co/readingtown/member/dto/request/FollowBulkCheckRequestDto.java
  member/src/main/java/kr/co/readingtown/member/dto/request/OnboardingRequestDto.java
  member/src/main/java/kr/co/readingtown/member/dto/request/StarRatingRequestDto.java
  member/src/main/java/kr/co/readingtown/member/dto/request/UpdateProfileRequestDto.java
  member/src/main/java/kr/co/readingtown/member/dto/request/UpdateTownRequestDto.java
  member/src/main/java/kr/co/readingtown/member/dto/response/DefaultProfileResponseDto.java
  member/src/main/java/kr/co/readingtown/member/dto/response/FollowerResponseDto.java
  member/src/main/java/kr/co/readingtown/member/dto/response/FollowingResponseDto.java
  member/src/main/java/kr/co/readingtown/member/dto/response/MemberSearchResponseDto.java
  member/src/main/java/kr/co/readingtown/member/dto/response/PartnerProfileResponseDto.java
  member/src/main/java/kr/co/readingtown/member/dto/response/ProfileResponseDto.java
  member/src/main/java/kr/co/readingtown/member/dto/response/StarRatingResponseDto.java
  member/src/main/java/kr/co/readingtown/member/exception/MemberErrorCode.java
  member/src/main/java/kr/co/readingtown/member/exception/MemberException.java
  member/src/main/java/kr/co/readingtown/member/externalapi/ExternalMemberController.java
  member/src/main/java/kr/co/readingtown/member/repository/MemberRepository.java
  member/src/main/java/kr/co/readingtown/member/service/KakaoLocationService.java
  member/src/main/java/kr/co/readingtown/member/service/LocationService.java
  member/src/main/java/kr/co/readingtown/member/service/MemberService.java
  member/src/test/java/kr/co/readingtown/member/service/MemberServiceTest.java
  rental/src/main/java/kr/co/readingtown/rental/domain/ExchangeMatch.java
  social/src/main/java/kr/co/readingtown/social/dto/request/FollowBulkCheckRequestDto.java
  social/src/main/java/kr/co/readingtown/social/exception/FollowErrorCode.java
  social/src/main/java/kr/co/readingtown/social/exception/FollowException.java
  social/src/main/java/kr/co/readingtown/social/internalapi/InternalFollowController.java
  social/src/main/java/kr/co/readingtown/social/repository/FollowRepository.java
  social/src/main/java/kr/co/readingtown/social/service/FollowService.java
Labels: ✨feat, 🌿refactor, 📃chore

#41 Feat: WebSocket 초기 설정
  chat/build.gradle
  chat/src/main/java/kr/co/readingtown/chat/config/WebsocketConfig.java
  chat/src/main/java/kr/co/readingtown/chat/handler/WebsocketHandler.java
  chat/src/main/resources/static/chat.html
  member/src/main/java/kr/co/readingtown/member/service/MemberService.java
Labels: ✨feat

#45 Feat: 변경된 모듈 적용
  api/build.gradle
  chat/src/main/java/kr/co/readingtown/chat/domain/Chatroom.java
  member/src/main/java/kr/co/readingtown/member/domain/Member.java
  member/src/main/java/kr/co/readingtown/member/domain/MemberBookstore.java
  rental/src/main/java/kr/co/readingtown/rental/domain/ExchangeMatch.java
  rental/src/main/java/kr/co/readingtown/rental/domain/ExchangeStatus.java
  rental/src/main/java/kr/co/readingtown/rental/domain/Rental.java
  rental/src/main/java/kr/co/readingtown/rental/domain/enums/ExchangeStatus.java
  rental/src/main/java/kr/co/readingtown/rental/domain/enums/RequestStatus.java
  settings.gradle
Labels: ✨feat

#48 Feat: 채팅 관련 기능
  api/src/main/java/kr/co/readingtown/swagger/SwaggerConfig.java
  chat/src/main/java/kr/co/readingtown/chat/domain/Chatroom.java
  chat/src/main/java/kr/co/readingtown/chat/domain/Message.java
  chat/src/main/java/kr/co/readingtown/chat/dto/response/ChatExchangedBookInfoResponse.java
  chat/src/main/java/kr/co/readingtown/chat/dto/response/ChatroomPreviewResponseDto.java
  chat/src/main/java/kr/co/readingtown/chat/dto/response/CursorPagingResponseDto.java
  chat/src/main/java/kr/co/readingtown/chat/dto/response/MessageListResponseDto.java
  chat/src/main/java/kr/co/readingtown/chat/dto/response/MessageResponseDto.java
  chat/src/main/java/kr/co/readingtown/chat/exception/ChatErrorCode.java
  chat/src/main/java/kr/co/readingtown/chat/exception/ChatException.java
  chat/src/main/java/kr/co/readingtown/chat/externalapi/ExternalChatController.java
  chat/src/main/java/kr/co/readingtown/chat/integration/bookhouse/BookhouseClient.java
  chat/src/main/java/kr/co/readingtown/chat/repository/ChatroomRepository.java
  chat/src/main/java/kr/co/readingtown/chat/repository/MessageRepository.java
  chat/src/main/java/kr/co/readingtown/chat/service/ChatService.java
Labels: ✨feat

#50 Feat/46 exchange status chat
  bookhouse/src/main/java/kr/co/readingtown/bookhouse/domain/Bookhouse.java
  bookhouse/src/main/java/kr/co/readingtown/bookhouse/domain/ExchangeStatus.java
  bookhouse/src/main/java/kr/co/readingtown/bookhouse/dto/request/ExchangeRequestDto.java
  bookhouse/src/main/java/kr/co/readingtown/bookhouse/dto/response/AcceptExchangeResponseDto.java
  bookhouse/src/main/java/kr/co/readingtown/bookhouse/dto/response/BookPreviewResponseDto.java
  bookhouse/src/main/java/kr/co/readingtown/bookhouse/dto/response/ExchangeResponseDto.java
  bookhouse/src/main/java/kr/co/readingtown/bookhouse/dto/response/ExchangingBookDetail.java
  bookhouse/src/main/java/kr/co/readingtown/bookhouse/dto/response/ExchangingBookResponse.java
  bookhouse/src/main/java/kr/co/readingtown/bookhouse/exception/BookhouseErrorCode.java
  bookhouse/src/main/java/kr/co/readingtown/bookhouse/exception/BookhouseException.java
  bookhouse/src/main/java/kr/co/readingtown/bookhouse/externalapi/ExternalBookhouseController.java
  bookhouse/src/main/java/kr/co/readingtown/bookhouse/externalapi/ExternalExchangeStatusController.java
  bookhouse/src/main/java/kr/co/readingtown/bookhouse/internalapi/InternalExchangeStatusController.java
  bookhouse/src/main/java/kr/co/readingtown/bookhouse/repository/BookhouseRepository.java
  bookhouse/src/main/java/kr/co/readingtown/bookhouse/repository/ExchangeStatusRepository.java
  bookhouse/src/main/java/kr/co/readingtown/bookhouse/service/BookhouseService.java
  bookhouse/src/main/java/kr/co/readingtown/bookhouse/service/ExchangeStatusService.java
  bookhouse/src/test/java/kr/co/readingtown/bookhouse/service/BookhouseServiceTest.java
  bookhouse/src/test/java/kr/co/readingtown/bookhouse/service/ExchangeStatusServiceTest.java
  chat/src/main/java/kr/co/readingtown/chat/externalapi/ExternalChatController.java
  chat/src/main/java/kr/co/readingtown/chat/integration/bookhouse/BookhouseClient.java
  chat/src/main/java/kr/co/readingtown/chat/integration/bookhouse/BookhouseUpdater.java
  chat/src/main/java/kr/co/readingtown/chat/service/ChatService.java
  common/build.gradle
  member/src/main/java/kr/co/readingtown/member/client/BookhouseClient.java
  member/src/main/java/kr/co/readingtown/member/domain/Member.java
  member/src/main/java/kr/co/readingtown/member/dto/response/internal/ExchangingBookResponseDto.java
  member/src/main/java/kr/co/readingtown/member/externalapi/ExternalMemberController.java
  member/src/main/java/kr/co/readingtown/member/integration/bookhouse/BookhouseClient.java
  member/src/main/java/kr/co/readingtown/member/integration/bookhouse/BookhouseReader.java
  member/src/main/java/kr/co/readingtown/member/integration/bookhouse/FollowClient.java
  member/src/main/java/kr/co/readingtown/member/service/MemberService.java
Labels: ✨feat, 🧪test
